import { isValidElement, useMemo, type ComponentPropsWithoutRef, type ReactNode } from 'react';
import ReactMarkdown, { type Components, type Options } from 'react-markdown';
import { Link } from 'react-router-dom';
import rehypeExternalLinks from 'rehype-external-links';
import rehypeHighlight from 'rehype-highlight';
import rehypeRaw from 'rehype-raw';
import rehypeSanitize from 'rehype-sanitize';
import remarkEmoji from 'remark-emoji';
import remarkGfm from 'remark-gfm';
import { MermaidBlock } from '@/components/MermaidBlock';
import { remarkCardLinks } from '@/lib/remark-card-links';
import '@/styles/highlight.css';

type MarkdownRendererProps = {
  children: string;
  // Card-link autolinking context (card #273). Both must be present to enable
  // `#NNN` → card-link rewriting; omit them and the renderer behaves exactly as
  // before (plain markdown, no autolinking — e.g. board-less render contexts).
  boardSlug?: string;
  cardNumbers?: Set<number>;
};

function findMermaidCode(children: ReactNode): string | null {
  if (!isValidElement(children)) return null;
  const props = children.props as { className?: string; children?: ReactNode };
  if (props.className === 'language-mermaid') {
    return String(props.children).replace(/\n$/, '');
  }
  return null;
}

// Internal card links generated by remarkCardLinks are relative (`/boards/...`).
// Render those as a React Router <Link> for client-side navigation; pass any
// other anchor (external links carrying target/rel from rehype-external-links)
// through unchanged.
function isInternalHref(href: string | undefined): href is string {
  return typeof href === 'string' && href.startsWith('/');
}

function MarkdownAnchor({ href, children, ...props }: ComponentPropsWithoutRef<'a'>) {
  if (isInternalHref(href)) {
    return <Link to={href}>{children}</Link>;
  }
  return (
    <a href={href} {...props}>
      {children}
    </a>
  );
}

const markdownComponents: Components = {
  pre({ children: preChildren, ...props }) {
    const mermaidCode = findMermaidCode(preChildren);
    if (mermaidCode !== null) {
      return <MermaidBlock>{mermaidCode}</MermaidBlock>;
    }
    return <pre {...props}>{preChildren}</pre>;
  },
  a: MarkdownAnchor,
};

type RemarkPlugins = NonNullable<Options['remarkPlugins']>;

export function MarkdownRenderer({ children, boardSlug, cardNumbers }: MarkdownRendererProps) {
  const remarkPlugins = useMemo<RemarkPlugins>(() => {
    const plugins: RemarkPlugins = [remarkGfm, remarkEmoji];
    if (boardSlug && cardNumbers) {
      plugins.push([remarkCardLinks, { boardSlug, cardNumbers }]);
    }
    return plugins;
  }, [boardSlug, cardNumbers]);

  return (
    <ReactMarkdown
      remarkPlugins={remarkPlugins}
      rehypePlugins={[
        rehypeRaw,
        rehypeSanitize,
        [rehypeHighlight, { plainText: ['mermaid'] }],
        [rehypeExternalLinks, { target: '_blank', rel: ['noopener', 'noreferrer'] }],
      ]}
      components={markdownComponents}
    >
      {children}
    </ReactMarkdown>
  );
}
